### ISSUE TITLE
update to angular4

### ISSUE THREAD

**Issue by softboy99** [bfwg/springboot-jwt-starter#2]
Hi,
Could you please update the starter to angular4? which is different largely to angular 1.x, Thanks.

**Comment by bfwg** [comment]
Hi @softboy99 ,

Yes, but this requires quite some work. I'm going to create a PR for this, please be patient. 😄

**Comment by softboy99** [comment]
waiting for your good news,Thanks.

**Comment by softboy99** [comment]
Hi,
have you finished?

**Comment by bfwg** [comment]
@softboy99 Yes, I have just finished the Angular4 update. Instead of using this repository, I chose to create a different repository due to the fact that it requires the repository structure to change quite dramatically. 
Please checkout [angular-spring-starter](https://github.com/bfwg/angular-spring-starter)
